/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.soluciones.Controlador;
import java.awt.TextField;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author braya
 */
public class VntVista extends javax.swing.JFrame {
    private JLabel[] filosofos;
    private JLabel[] tenedor;
    private JTextField[] vCome;
    
    /**
     * Creates new form VntVista
     */
    public VntVista(){
        initComponents();
        
        
        filosofos = new JLabel[5];
        filosofos[0] = filosofo1;
        filosofos[1] = filosofo2;
        filosofos[2] = filosofo3;
        filosofos[3] = filosofo4;
        filosofos[4] = filosofo5;
        
        tenedor = new JLabel[5];
        tenedor[0] = tenedor1;
        tenedor[1] = tenedor2;
        tenedor[2] = tenedor3;
        tenedor[3] = tenedor4;
        tenedor[4] = tenedor5;
        
        vCome = new JTextField[5];
        vCome[0] = txtcome1;
        vCome[1] = txtcome2;
        vCome[2] = txtcome3;
        vCome[3] = txtcome4;
        vCome[4] = txtcome5;
        
//        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo5 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        tenedor1 = new javax.swing.JLabel();
        tenedor2 = new javax.swing.JLabel();
        tenedor3 = new javax.swing.JLabel();
        tenedor4 = new javax.swing.JLabel();
        tenedor5 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProceso = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcome1 = new javax.swing.JTextField();
        txtcome2 = new javax.swing.JTextField();
        txtcome3 = new javax.swing.JTextField();
        txtcome4 = new javax.swing.JTextField();
        txtcome5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(675, 675));
        jPanel2.setPreferredSize(new java.awt.Dimension(625, 625));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/mesac.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 120, 512, 512);

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/avatar.png"))); // NOI18N
        filosofo1.setText("Filosofo 1");
        filosofo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(filosofo1);
        filosofo1.setBounds(90, 560, 90, 120);

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/avatar.png"))); // NOI18N
        filosofo2.setText("Filosofo 2");
        filosofo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(filosofo2);
        filosofo2.setBounds(-10, 190, 80, 130);

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/avatar.png"))); // NOI18N
        filosofo3.setText("Filosofo 3");
        filosofo3.setToolTipText("");
        filosofo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(filosofo3);
        filosofo3.setBounds(270, 0, 90, 120);

        filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/avatar.png"))); // NOI18N
        filosofo5.setText("Filosofo 5");
        filosofo5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo5.setFocusable(false);
        filosofo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(filosofo5);
        filosofo5.setBounds(445, 560, 90, 120);

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/avatar.png"))); // NOI18N
        filosofo4.setText("Filosofo 4");
        filosofo4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(filosofo4);
        filosofo4.setBounds(545, 195, 90, 120);

        tenedor1.setBackground(new java.awt.Color(0, 0, 0));
        tenedor1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/tenedor.png"))); // NOI18N
        tenedor1.setText("Tenedor");
        tenedor1.setToolTipText("");
        tenedor1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tenedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tenedor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tenedor1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tenedor1);
        tenedor1.setBounds(175, 480, 50, 70);

        tenedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/tenedor.png"))); // NOI18N
        tenedor2.setText("Tenedor");
        tenedor2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tenedor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tenedor2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tenedor2);
        tenedor2.setBounds(125, 245, 48, 70);

        tenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/tenedor.png"))); // NOI18N
        tenedor3.setText("Tenedor");
        tenedor3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tenedor3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tenedor3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tenedor3);
        tenedor3.setBounds(300, 160, 48, 70);

        tenedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/tenedor.png"))); // NOI18N
        tenedor4.setText("Tenedor");
        tenedor4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tenedor4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tenedor4);
        tenedor4.setBounds(460, 245, 48, 70);

        tenedor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/tenedor.png"))); // NOI18N
        tenedor5.setText("Tenedor");
        tenedor5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tenedor5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tenedor5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tenedor5);
        tenedor5.setBounds(420, 475, 48, 70);

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/button_iniciar.png"))); // NOI18N
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proceso problema"));

        txtProceso.setEditable(false);
        txtProceso.setColumns(20);
        txtProceso.setRows(5);
        jScrollPane1.setViewportView(txtProceso);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Filosofo 1");

        jLabel4.setText("Filosofo 2");

        jLabel5.setText("Filosofo 3");

        jLabel6.setText("Filosofo 4");

        jLabel7.setText("Filosofo 5");

        txtcome1.setEditable(false);
        txtcome1.setText("0");

        txtcome2.setEditable(false);
        txtcome2.setText("0");

        txtcome3.setEditable(false);
        txtcome3.setText("0");

        txtcome4.setEditable(false);
        txtcome4.setText("0");

        txtcome5.setEditable(false);
        txtcome5.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcome5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcome4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcome3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(467, 467, 467)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciar)
                        .addGap(241, 241, 241)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        int i, tenedor_izq, tenedor_der = 0;
        for (i = 0; i < filosofos.length; i++) {
            tenedor_izq = i - 1;
//            System.out.println("corriendo programa");
            if (tenedor_izq < 0) {
                tenedor_izq = 4;
            }
            tenedor_der = i;
            
            Controlador ctrl;
            ctrl = new Controlador(i,filosofos[i], tenedor[tenedor_der], tenedor[tenedor_izq], vCome[i], txtProceso);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntVista().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel filosofo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tenedor1;
    private javax.swing.JLabel tenedor2;
    private javax.swing.JLabel tenedor3;
    private javax.swing.JLabel tenedor4;
    private javax.swing.JLabel tenedor5;
    private javax.swing.JTextArea txtProceso;
    private javax.swing.JTextField txtcome1;
    private javax.swing.JTextField txtcome2;
    private javax.swing.JTextField txtcome3;
    private javax.swing.JTextField txtcome4;
    private javax.swing.JTextField txtcome5;
    // End of variables declaration//GEN-END:variables
}
